### PR TITLE
Set correct player sprite direction when pikachu is diving

### PR DESCRIPTION
**Pull request by disjukr**
Pikachu always looks at the other side, but when it divings, it have to look in the direction of diving.

### CODE REVIEW

**Comment by gorisanson** [comment]
@disjukr Wow! I was not aware of it. Thank a lot!

**Comment by ChrisLee1218** [comment]
I have problem with this online pika-volleyball. When I play with my laptop, it doesn't perceive my enter key.
My laptop is Zeus14 made by mpgio.
학교에서 이거 하고 싶습니다... ㅠㅠ Z키로도 퀵매치좀 하게 해주십사 부탁드리겠습니다

**Comment by gorisanson** [comment]
@ChrisLee1218 
Z키로도 퀵매치 시작할 수 있도록 업데이트했습니다!

**Comment by ChrisLee1218** [comment]
@gorisanson 감사합니다! 깃허브 가입만 해둔 터라 잘 몰라서 아무데나 글을 써버렸네요. 게임 재밌게 하겠습니다~!

**Pull request merged**
